Rewrite script

diff --git a/src/dl b/src/dl
--- a/src/dl
+++ b/src/dl
@@ -3,75 +3,98 @@
 # Functions
 usage() {
     cat << HERE
-Description: youtube-dl wrapper script script to store downloaded files in a specific directory.
-Usage: dl <DIRECTORY> <URL>
+Description: youtube-dl wrapper script that reads URLs to download from standard input.
+Usage: dl <OPTION> <ARGUMENT>
+
+Available options:
+
+    -a
+        Convert downloaded files to an audio format.
+
+    -d DIRECTORY
+        Save files in a directory, defaults to /tmp if not specified.
+
+    -h
+        Show script usage.
 
 Examples:
 
-dl /tmp "https://www.youtube.com/watch?v=jyCmnvBbm8Q"
+dl -a -d ~/Downloads
+dl -d ~/Videos
+dl -a
 
-dl will download URL "https://www.youtube.com/watch?v=jyCmnvBbm8Q" and store it in /tmp directory.
-
-
-NOTE: Quote the URL(s) to prevent errors with your shell.
 HERE
 }
 
 showError() {
-    printf '%b\n' "${LIGHT_RED}ERROR${RESET}: ${scriptName}: $1" >&2
+    printf '%b\n' "$1" >&2
 }
 
 download() {
-    for URL in $1; do
-        if youtube-dl -q --no-warnings --no-part --exec "mv {} ${DIRECTORY}" "$2" -- "${URL}" 2>&-; then                    # https://stackoverflow.com/questions/3012877/how-to-prevent-code-option-injection-in-a-bash-script#3012903
-            printf '%b\n' "${scriptName}: URL \"${URL}\" ${LIGHT_GREEN}downloaded successfully!${RESET}"
+    local failedDownloads=0 URLs
+
+    printf '%s\n\n' "Type the URL(s) to download press Control + D when finished."
+
+    mapfile -t URLs
+
+    [[ ${#URLs} -eq 0 ]] && { showError "No URL(s) to download."; exit 1; }
+
+    for URL in "${URLs[@]}"; do
+        if youtube-dl $1 --quiet --no-warnings --no-part --exec "mv {} ${DIRECTORY}" "${URL}" 2>&-; then
+            printf 'URL: %s\n' "\"${URL}\" downloaded successfully."
         else
-            showError "URL \"${URL}\" ${LIGHT_RED}could not be downloaded${RESET}"
+            showError "URL: \"${URL}\" could not be downloaded."
+            failedDownloads=$(( failedDownloads+=1 ))
             continue
         fi
     done
+
+    [[ ${#URLs[@]} -eq ${failedDownloads} ]] && { showError "\nNo URL(s) could be downloaded."; exit 1; }
 }
 
-# Global variables
-scriptName=${0##*/}
+readonly DEFAULT_DIR='/tmp'
 
-# Arguments
-DIRECTORY=$1
+# Handle interrupts.
+trap '{ showError "\nScript was interrupted."; exit 1; }' SIGINT
 
-# Constants
-readonly LIGHT_RED='\e[91m' LIGHT_GREEN='\e[92m' RESET='\e[0m'
+# Parse options.
+optionCount=0
 
-# Verify script has the proper amount of arguments.
-[[ $# -eq 0 ]] && { showError "No arguments\n"; usage; exit 1; }
-[[ $# -ge 2 ]] || { showError "Insufficient arguments.\n"; usage; exit 1; }
+while getopts ':ad:h' OPTION; do
+    optionCount=$(( optionCount+=1 ))
 
-# Validate DIRECTORY.
-if [[ ! -e "${DIRECTORY}" ]]; then
-    { showError "Destination \"${DIRECTORY}\" does not exist."; exit 1; }
-elif [[ ! -d "${DIRECTORY}" ]]; then
-    { showError "Destination \"${DIRECTORY}\" is not a directory."; exit 1; }
-elif [[ ! -w "${DIRECTORY}" ]]; then
-    { showError "Destination directory \"${DIRECTORY}\" is not writable, modify its permissions."; exit 1; }
+    case "${OPTION}" in
+        (a)
+            convertToAudio='true'
+        ;;
+        (d)
+            DIRECTORY="${OPTARG}"
+        ;;
+        (h)
+            { usage; exit 0; }
+        ;;
+        ('?')
+            { showError "Illegal option -\"${OPTARG}\"."; exit 1; }
+        ;;
+    esac
+done
+
+[[ ${optionCount} -eq 0 ]] && { showError "No options were selected."; exit 1; }
+
+# Assign directory if it was not specified.
+DIRECTORY="${DIRECTORY:-$DEFAULT_DIR}"
+
+# Validate directory.
+[[ -e "${DIRECTORY}" ]] || { showError "Can not save downloads in directory \"${DIRECTORY}\" it does not exist."; exit 1; }
+[[ -d "${DIRECTORY}" ]] || { showError "Can not save downloads in \"${DIRECTORY}\" it is not a directory."; exit 1; }
+[[ -w "${DIRECTORY}" ]] || { showError "Can not save downloads in \"${DIRECTORY}\" it does not have write permissions."; exit 1; }
+
+# Download URLs.
+if [[ ${convertToAudio} ]]; then
+    download '--extract-audio'
+else
+    download
 fi
 
-# Set a trap to handle interrupt signals.
-trap 'exit 1' SIGINT
-
-# Download URLs
-read -r -p 'Store download(s) as audio file(s)? y/n ' userReply
-
-# Remove all set traps.
+# Remove traps
 trap &> /dev/null
-
-shift
-case "${userReply}" in
-    ([Yy] | 'Yes' | 'yes')
-        download "$@" "--extract-audio"
-    ;;
-    ([Nn] | 'No' | 'no')
-        download "$@"
-    ;;
-    (*)
-        { showError "Invalid reply \"${userReply}\""; exit 1; }
-    ;;
-esac
