feat: show error if SHELL environment variable is unset or empty

diff --git a/src/si b/src/si
--- a/src/si
+++ b/src/si
@@ -71,7 +71,13 @@ else
 
 fi
 
-(( "${#SHELL}" )) && printf 'Shell: %s\n' "${SHELL##*/}"
+if (( "${#SHELL}" )); then
+    printf 'Shell: %s\n' "${SHELL##*/}"
+
+else
+    printf 'Shell: Could not be detected' >&2
+
+fi
 
 p=0
 
